'type: question/stack overflow':
  comment: |
    We use the issue tracker exclusively for bug reports and feature requests.
    This issue appears to be a general usage or support question.
    Instead, please ask a question on Stack Overflow with the `wix-react-native-navigation` tag or on [Discord](https://discord.gg/DhkZjq2).
  close: true
  lock: false
