language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2
    - $ANDROID_HOME/licenses

before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  - set -e
  - export ANDROID_HOME=$HOME/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  - ./scripts/clean.sh

script:
  - yarn run lint
  - yarn run test:js
  - ./scripts/installAndroidSDK.sh
  - yarn run test:android

after_script:
  - echo "BUILD FINISHED"
