compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: workspaces

npmMinimalAgeGate: 14d

nodeLinker: node-modules

npmRegistryServer: "https://npm.dev.wixpress.com"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
