require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


def all_pods  
  config = use_native_modules!
  
  flags = get_default_flags()
  
  use_react_native!(
    :path => "../../node_modules/react-native",
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/../.."
  )
  
  pod 'ReactNativeNavigation', :path => '../../'
  pod 'HMSegmentedControl'
end

post_install do |installer|
  react_native_post_install(installer, "../../node_modules/react-native", :mac_catalyst_enabled => false)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  # This is to resolve "'shared_timed_mutex' is unavailable: introduced in iOS 10.0" error
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
    end
  end
end

target 'playground' do
  all_pods
end

target 'NavigationTests' do
  all_pods
  pod 'OCMock'
end

target 'NavigationIOS12Tests' do
  all_pods
  pod 'OCMock'
end

target 'SnapshotTests' do
  all_pods
  pod 'OCMock'
end