steps:
  - block: ":rocket: Release!"
    prompt: "Fill out the details for release"
    if: 'build.message =~ /^release\$/i'
    fields:
      - text: "VERSION"
        key: "version"
      - text: "NPM_TAG"
        key: "npm-tag"
        default: 'null'
        required: false
      - text: "BUILD_DOCUMENTATION_VERSION"
        key: "build-documentation-version"
        default: 'null'
        hint: 'Leave NULL if no version is specified'
      - text: "REMOVE_DOCUMENTATION_VERSION"
        key: "remove-documentation-version"
        default: 'null'
        hint: 'Leave NULL if no version is specified'
  
  - label: ":js: JS"
    command:
    - "nvm install"
    - "npm install"
    - "npm run test-js"
    key: "js_build"
    
  - label: ":android: Android - unit"
    command:
    - "nvm install"
    - "npm install"
    - "npm run test-unit-android -- --release"
    key: "android_build_unit"
    
  - label: ":android: Android - e2e"
    command:
    - "nvm install"
    - "npm install"
    - "npm run test-e2e-android-multi -- --release --headless --verbose --ci"
    key: "android_build_e2e"

  - label: ":ios: iOS - unit"
    command:
    - "nvm install"
    - "npm install"
    - "npm run test-unit-ios -- --release"
    key: "ios_build_unit"
  
  - label: ":ios: iOS - e2e"
    command:
    - "nvm install"
    - "npm install"
    - "npm run test-e2e-ios -- --release --multi --ci"
    key: "ios_build_e2e"
    
   - label: ":ios: iOS - snapshot"
    command:
    - "nvm install"
    - "npm install"
    - "npm run test-snapshot-ios -- --release"
    key: "ios_build_snapshot"

  - label: ":package: Publish"
    env:
    if: "build.pull_request.id == null"
    command:
    - "nvm install"
    - "npm install"
    - "npm run release"
    depends_on:
    - "js_build"
    - "android_build_unit"
    - "android_build_e2e"
    - "ios_build_unit"
    - "ios_build_e2e"
    - "ios_build_snapshot"
