#!/usr/bin/env bash
# Updates spm/binary-manifest.json with url and checksum for Package.swift binaryTarget.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ZIP_PATH="$ROOT/build/spm/ReactNativeNavigation.xcframework.zip"
MANIFEST="$ROOT/spm/binary-manifest.json"

VERSION=""
URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) VERSION="$2"; shift 2 ;;
    --url) URL="$2"; shift 2 ;;
    --zip) ZIP_PATH="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[[ -n "$VERSION" ]] || { echo "Usage: $0 --version X.Y.Z --url <https://...zip> [--zip path]" >&2; exit 1; }
[[ -n "$URL" ]] || { echo "--url required" >&2; exit 1; }
[[ -f "$ZIP_PATH" ]] || { echo "Zip not found: $ZIP_PATH (run ./scripts/build-ios-xcframework.sh first)" >&2; exit 1; }

if command -v swift >/dev/null 2>&1; then
  CHECKSUM=$(swift package compute-checksum "$ZIP_PATH")
else
  CHECKSUM=$(shasum -a 256 "$ZIP_PATH" | awk '{print $1}')
fi

node -e "
const fs = require('fs');
const manifest = {
  version: process.argv[1],
  url: process.argv[2],
  checksum: process.argv[3],
  note: 'Generated by scripts/update-spm-binary-manifest.sh',
};
fs.writeFileSync(process.argv[4], JSON.stringify(manifest, null, 2) + '\n');
" "$VERSION" "$URL" "$CHECKSUM" "$MANIFEST"

echo "Updated $MANIFEST"
cat "$MANIFEST"
